[package]
name = "bloom-password-verfier"
version = "0.1.0"
authors = ["goutham"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]


[dependencies]

bloom = "0.2.0"
wasm-bindgen = "0.2"